RUN yum -y install wget libSM cairo cups-libs && \
    wget http://downloadarchive.documentfoundation.org/libreoffice/old/6.4.0.2/rpm/x86_64/LibreOffice_6.4.0.2_Linux_x86-64_rpm.tar.gz && \
    tar -xvf LibreOffice_6.4.0.2_Linux_x86-64_rpm.tar.gz && \
    yum localinstall -y LibreOffice_6.4.0.2_Linux_x86-64_rpm/RPMS/*.rpm && \
    rm -Rf LibreOffice_6.4.0.2_Linux_x86-64_rpm && \
    rm -f LibreOffice_6.4.0.2_Linux_x86-64_rpm.tar.gz

ENV OFFICE_STARTING_PORT 50000